#ifndef SPACE_TRAFFIC_DEFLECTOR_H
#define SPACE_TRAFFIC_DEFLECTOR_H

enum DeflectorTypes {
    CLASS_1_DEFLECTOR = 1,
    CLASS_2_DEFLECTOR,
    CLASS_3_DEFLECTOR,
    PHOTONIC_DEFLECTOR
};

#endif //SPACE_TRAFFIC_DEFLECTOR_H
